version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      all-root-deps:
        patterns: ['*']
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
    groups:
      all-backend-deps:
        patterns: ['*']
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      all-frontend-deps:
        patterns: ['*']
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
